version: '3.8'

services:
  postgres:
    container_name: "lab1-postgres"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data

  keycloak_db:
    container_name: "keycloak_db"
    image: postgres
    restart: unless-stopped
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    volumes:
      - ./volumes/pg_data_keycloak:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8484:8080"
    depends_on:
      - keycloak_db
    links:
      - "keycloak_db:keycloak_db"
    volumes:
      - ./volumes/logs:/var/log/keycloak
      - ./volumes/providers:/opt/keycloak/providers